name: Spring

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest  # ✅ fixed (was: run-on)

    steps:
      - name: Checkout source
        uses: actions/checkout@v3  # ✅ fixed (was: action/checkout)

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Build with Maven
        run: mvn clean install -DskipTests
